use_frameworks!

platform :ios, '12.0'

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'ZHHNetworkHelper_Example' do
  pod 'ZHHNetworkHelper', :path => '../'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'ZHHUnicodeReadable'
  pod 'YYText'
  
  target 'ZHHNetworkHelper_Tests' do
    inherit! :search_paths

    
  end
end
